import { PropsWithChildren, useEffect, useRef } from 'react';
import { Empty, Spin, Tag } from 'antd';
import * as PIXI from 'pixi.js';

export const statusMeta: Record<string, { label: string; color: string }> = { draft: { label: '草稿', color: 'default' }, review: { label: '审核中', color: 'blue' }, published: { label: '已发布', color: 'green' }, deprecated: { label: '已废弃', color: 'orange' }, archived: { label: '已归档', color: 'default' }, queued: { label: '排队中', color: 'gold' }, processing: { label: '生成中', color: 'processing' }, succeeded: { label: '已完成', color: 'green' }, failed: { label: '失败', color: 'red' }, cancelled: { label: '已取消', color: 'default' } };
export function StatusTag({ status }: { status: string }) { const meta = statusMeta[status] || { label: status, color: 'default' }; return <Tag color={meta.color}>{meta.label}</Tag>; }
export function PageHeader({ eyebrow, title, description, actions }: { eyebrow: string; title: string; description: string; actions?: React.ReactNode }) { return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{actions && <div className="page-actions">{actions}</div>}</div>; }
export function Loading({ loading, children, empty = false }: PropsWithChildren<{ loading: boolean; empty?: boolean }>) { if (loading) return <div className="loading"><Spin /></div>; if (empty) return <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="还没有内容，从右上角开始创建" />; return <>{children}</>; }
export function PixiMapPreview() {
  const host = useRef<HTMLDivElement>(null);
  useEffect(() => { let disposed = false; const app = new PIXI.Application(); (async () => { await app.init({ width: 760, height: 360, background: '#0c1119', antialias: true, resolution: Math.min(devicePixelRatio, 2) }); if (disposed || !host.current) return; host.current.appendChild(app.canvas); const grid = new PIXI.Graphics(); for (let x = 0; x <= 760; x += 40) grid.moveTo(x, 0).lineTo(x, 360); for (let y = 0; y <= 360; y += 40) grid.moveTo(0, y).lineTo(760, y); grid.stroke({ color: '#223043', width: 1, alpha: .55 }); app.stage.addChild(grid); const path = new PIXI.Graphics().moveTo(40, 280).bezierCurveTo(190, 270, 180, 80, 360, 110).bezierCurveTo(520, 140, 555, 290, 720, 190).stroke({ color: '#b8ff5a', width: 18, alpha: .16 }); app.stage.addChild(path); const towers = [[170, 185], [360, 180], [555, 210]]; towers.forEach(([x,y], i) => { const g = new PIXI.Graphics().circle(0, 0, 20).fill(i === 1 ? '#75e6ff' : '#b8ff5a').circle(0,0,31).stroke({ color: '#fff', width: 1, alpha: .25 }); g.position.set(x,y); app.stage.addChild(g); }); const marker = new PIXI.Graphics().circle(0,0,9).fill('#ff766f'); app.stage.addChild(marker); let t = 0; app.ticker.add((ticker) => { t += ticker.deltaTime * .012; marker.x = 40 + Math.min(t,1) * 680; marker.y = 220 - Math.sin(Math.min(t,1) * Math.PI * 2.2) * 105; if (t > 1) t = 0; }); })(); return () => { disposed = true; app.destroy(true, { children: true }); }; }, []);
  return <div className="pixi-preview" ref={host} />;
}
